import { createApp } from 'vue';
import App from './App.vue';
import PrimeVue from 'primevue/config';
import ToastService from 'primevue/toastservice';
import BadgeDirective from 'primevue/badgedirective';
const app = createApp(App);
app.use(PrimeVue);
app.use(ToastService);
app.use(BadgeDirective);
app.mount('#app');